.TH Software Sets
.PP
Software sets are collections of programs used in the pipelines with their complete paths and sets of standard parameters.
.SH Standard Bin
.TP
Standard Bin is the default set of programs and is used by all the pipelines.  The programs in Standard Bin are specified in a JSON (Javascript Object Notation) configuration file.
.TP
.IP Config_file::
standardbin.json
.TP
.IP Pipelines_included::
exomeseq,rnaseq,mirseq
.TP
.IP Structure::
{
     "bin": {
    "exomeseq": {
        "NOVOALIGN": "/usr/local/apps/novocraft/3.04.04/novoalign",
        "NOVOSORT": "/usr/local/apps/novocraft/3.04.04/novosort",
        "ANNOVAR1": "/usr/local/apps/ANNOVAR/2015-03-22/convert2annovar.pl",
        "ANNOVAR2": "/usr/local/apps/ANNOVAR/2015-03-22/table_annovar.pl",
        "INDEXBAM": "java -jar /usr/local/apps/picard/1.129/picard.jar BuildBamIndex", ...

.TP
.IP Programs_included:

exomeseq::
ANNOVAR, BAMTOOLS, BEDTOOLS, BICSEQ, BWA, COVCALC, COVFREQ, FASTQC, FASTQ_SCREEN, FIRSTANNO, GATK, INDEXBAM, MARKDUPS, MUTECT, NGSQCTOOLKIT, NOVOALIGN, NOVOSORT, PICARDTOOLS, PICHIST, QCAL, QUALIMAP, READDIST, SAMTOOLS, SNPEFF, SNPSIFT, STAR, SVDETECT, TRIMMOMATIC, VARSCAN

genomeseq::
ANNOVAR1, ANNOVAR2, BAMTOOLS, BEDTOOLS, BICSEQ, BWA, COVCALC, COVFREQ, FASTQC, FASTQ_SCREEN, FIRSTANNO, GATK, INDEXBAM, MARKDUPS, MUTECT, NGSQCTOOLKIT, NOVOALIGN, NOVOSORT, PICARD1, PICARD2, PICARD3, PICHIST, QCAL, QUALIMAP, READDIST, SAMTOOLS, SNPEFF, SNPSIFT, STAR, SVDETECT, TRIMMOMATIC, VARSCAN

rnaseq::
BWA, CHKQC, FASTQC, PICARD, RNASEQC, STAR, SUBREAD, TRIMMOMATIC

mirseq::
BEDTOOLS, BOWTIE, CUTADAPT, FASTQC, GATK_JAR, HTSEQ, JAVA, MIRDEEP2, NGS_PORTAL, PDFAPI2_PM, PICARD, PYTHON, RANDFOLD, RSCRIPT, SAMTOOLS, SCRIPT, SQUID, VCFTOOLS, VCFTOOLS_PERLLIB, VIENNA
