.ll 6.4i
.TH Annotation Sets
.SH Annotation Set hg19

hg19 contains a set of reference files for the analyss of human data based on the Human Genome Referecen version 19 of UCSC.  This build is equivalent to the February 2009 human reference sequence (GRCh37) produced by the Genome Reference Consortium.

.TP
.IP References_included::

.SH Annotaton Set mm10

mm10 contains a set of reference file for the analysis of mouse data based on the Mouse Genome Reference version 10 of UCSC. This build is equivalent to the December 2011 Mus musculus assembly (Genome Reference Consortium Mouse Build 38 produced by the Mouse Genome Reference Consortium.
.TP
.IP References_included::
