.ll 6.4i
.TH RNASeq mincount and minsamp
.SH Mincount and Minsamp
.TP
Mincount is the minimum number of reads required to count a gene as expressed in a single sample.  This parameter is paired with Minsamples which is the number of samples required to have Mincount reads in order to count a gene as expressed in a dataset.
