.ll 6.4i
.TH RNASeq Strand
.SH Strand of Reads
.TP
.PP Specifies the strand of the reads.
.IP Unstranded
Reads come from both sense and anti-sense strands.  Value is 0.
.IP Sense
Reads originate from the sense strand only. Value is 1.
.IP Antisense
Reads originage from ant-sense strand only. Value is 2.

