---
title: "JackStraw Report"
author: "CCBR scRNAseq pipeline"
output: html_document
params:
  seurat: "/path/to/seurat/save"
  projectId: "<projectId>"
  projectDesc: "<desc>"
---


```{r headers, include=FALSE, warning=FALSE, message=FALSE}
projectId<-params$projectId
projectDesc<-params$projectDesc
dateandtime<-format(Sys.time(), "%a %b %d %Y - %X")
so_save<-params$seurat
```

### **Project:**
####    *`r projectId`*
### **Description:** 
####    *`r projectDesc`*
### **Report generated:** 
####    *`r dateandtime`* 

```{r setup, echo=FALSE, warning=FALSE,message=FALSE}
library(knitr)
library(Seurat)
library(dplyr)
library(Matrix)

so <- readRDS(so_save)
```

### **Seurat JackStraw Plots**

```{r Seurat_jackstraw, echo=FALSE,warning=FALSE,message=FALSE,fig.height=20}
#Generates jackstraw plots for 20 PCs
#Computationally intesnive, may not be necessary if elbow plot looks good
#But can be used as additional insight for PC selection for tSNE
so <- JackStraw(so, num.replicate = 100, display.progress=FALSE)
saveRDS(so, paste0(projectId,"_jackstraw_seurat_object.rds"))
JackStrawPlot(so, PCs = 1:20, nCol=2)
```