---
title: "Cluster Report"
author: "CCBR scRNAseq pipeline"
output: html_document
params:
  seurat: "/path/to/seurat/save"
  pcs: 10
  resolution: 0.6
  projectId: "<projectId>"
  projectDesc: "<desc>"
---


```{r headers, include=FALSE, warning=FALSE, message=FALSE}
projectId<-params$projectId
projectDesc<-params$projectDesc
dateandtime<-format(Sys.time(), "%a %b %d %Y - %X")
so_save<-params$seurat
pcs<-params$pcs
res<-params$resolution
```

### **Project:**
####    *`r projectId`*
### **Description:** 
####    *`r projectDesc`*
### **Report generated:** 
####    *`r dateandtime`* 

```{r setup, echo=FALSE, warning=FALSE,message=FALSE}
library(knitr)
library(rgl)
library(Seurat)
library(dplyr)
library(Matrix)
library(methods)
library(igraph)
#library(TSCAN) #NOT INSTALLED ON BOIWULF YET
so <- readRDS(so_save)
```

### **tSNE**

```{r Seurat_tsne, echo=FALSE,warning=FALSE,message=FALSE}
#Outputs tSNE with clustering given pc selection and cluster resolution
#Reminder: Default resolution is around 0.6, lower res = less clusters
so <- FindClusters(so, reduction.type = "pca", dims.use = 1:pcs, resolution = res, print.output = 0, save.SNN = T, random.seed=1234567, temp.file.location=getwd())
so <- RunTSNE(so, dims.use = 1:pcs, do.fast = T)
TSNEPlot(so,do.label=T,do.return = T)
tsplot <- TSNEPlot(so,do.label=T,do.return = T)
saveRDS(so, paste0(projectId,"_cluster_seurat_object_",pcs,"_",res,".rds"))
```

```{r Seurat_genes, echo=FALSE,warning=FALSE,message=FALSE,results='hide'}
#Generates html tables for the top 100 gene markers that identify each cluster
#Also saves the full table for each cluster as text file
nclusts <- length(levels(so@ident))
glist <- list()
tables <- htmltools::tagList()
for(i in 1:nclusts){
	glist[[i]]<-FindMarkers(so,ident.1=i-1,min.pct=0.25)
	tables[[i]] <- DT::datatable(glist[[i]][1:100,], caption=htmltools::tags$caption(paste0("Top 100 gene markers for cluster #",(i-1)) ,style="color:red; font-size: 12px" ),rownames=T)
	write.table(glist[[i]],file=paste0(projectId,"_seurat_",pcs,"_",res,"_cluster_",(i-1),".txt")
	            ,sep="\t",quote=F)
}
```

### **Top 10 Cluster Marker Heatmap**
```{r markerheatmap, echo=FALSE,warning=FALSE,message=FALSE}
#Generates a heatmap of subsampled cells of each cluster vs marker genes
#Useful for validating clustering
so.markers <- FindAllMarkers(object = so, only.pos = TRUE, min.pct = 0.25, thresh.use = 0.25)
top10 <- so.markers %>% group_by(cluster) %>% top_n(10, avg_logFC)
DoHeatmap(object = so, genes.use = top10$gene, slim.col.label = TRUE, remove.key = TRUE)
```

### **Gene Lists**

```{r Seurat_genes_table, echo=FALSE,warning=FALSE,message=FALSE,results='asis'}
#Outputs the previously generated html tables
tables
```


```{r tscan, echo=FALSE,warning=FALSE,message=FALSE}
#This is some implementation of Maggie's TSCAN code
#Temporarily placed here for later reference
#It will have to be its own RMD at some point, and run as needed
#I'm not sure if I got this to actually work as I wanted...
#But good luck to whoever tries it out!

# pca.clus=data.frame(clusid=so@ident,so@dr$pca@cell.embeddings[,1:pcs])
# meanPC = pca.clus %>% group_by(clusid) %>% summarise_all(funs(mean)) 
# datclust=vector("list",4)
# names(datclust) = c("pcareduceres","MSTtree","clusterid","clucenter")  
# clucenter=as.matrix(meanPC[,-1])
# rownames(clucenter)=seq(1,dim(clucenter)[1],1)
# dp <- as.matrix(dist(clucenter))
# gp <- graph.adjacency(dp, mode = "undirected", weighted = TRUE)
# dp_mst <- minimum.spanning.tree(gp)

# datclust$pcareduceres=as.matrix(pca.clus[,-1])
# rownames(datclust$pcareduceres)=seq(nrow(datclust$pcareduceres))
# datclust$MSTtree=dp_mst
# datclust$clusterid=as.integer(so@ident)
# names(datclust$clusterid) = seq(length(datclust$clusterid))
# clucenter=as.matrix(meanPC[,-1])
# datclust$clucenter=as.matrix(clucenter)
# rownames(datclust$clucenter)=NULL
# colnames(datclust$clucenter)=NULL
# datorderTSCAN <- TSCAN::TSCANorder(datclust, orderonly = F, listbranch = T)

# draw.tSNE.time <- function(obj,p1,pt,num){
#   objname=obj@project.name
#   dtime.df=data.frame(samp=pt[[num]]$sample_name,
#                       time=pt[[num]]$Pseudotime)
#   clusmat=data.frame(tsne1=p1$data$tSNE_1,
#                      tsne2=p1$data$tSNE_2)
#   rownames(clusmat)=seq(nrow(clusmat))
#   clusmat$time=0
#   clusmat$time=dtime.df$time[match(rownames(clusmat),as.character(dtime.df$samp))]
#   ggplot(clusmat, aes(x=tsne1, y=tsne2)) +
#     theme_bw() +
#     theme(legend.title=element_blank()) +
#     geom_point(aes(colour=time),size=0.5) +
#     scale_color_gradient(low = "grey", high = "blue") +
#     ggtitle(names(pt)[[num]]) +
#     xlab("tsne-1") + ylab("tsne-2")
# }

# for (i in 1:length(datorderTSCAN)){
#   print(draw.tSNE.time(so,tsplot,datorderTSCAN,i))
# }
```
