rule all_exomeseq_somatic:
    input:  expand("{s}"+".realign.bam",s=samples),
            expand("mutect2/{p}"+".FINAL.vcf",p=pairs),
            expand("mutect/{p}"+".FINAL.vcf",p=pairs),
            expand("strelka/{p}"+".vcf",p=pairs),
            expand("mutect2/oncotator/{p}"+".maf",p=pairs),
            expand("strelka/oncotator/{p}"+".maf",p=pairs),
            expand("mutect/oncotator/{p}"+".maf",p=pairs),
            "strelka",
            "mutect2",
            "cnvkit",
            "mutect",
            "delly",
            "germline_snps.vcf",
            expand("cnvkit/{p}"[1]+".cnr",
#            expand("cnvkit/{p}"[1]+".cns",
#            expand("delly/{p}"[1]+"del.bcf",
#            expand("delly/{p}"[1]+"ins.bcf",
#            expand("delly/{p}"[1]+"dup.bcf",
#            expand("delly/{p}"[1]+"tra.bcf",
#            expand("delly/{p}"[1]+"inv.bcf",
            "mutect2/merged_somatic.vcf",
            "mutect2/merged_somatic_snpEff.vcf",
            "variants.bed",
            "full_annot.txt.zip",
            "sample_network.bmp",
            "variants.database",
            "mutect2/oncotator/mutect2_variants.maf",
            "mutect2/mutsigCV/somatic.sig_genes.txt",
            "strelka/oncotator/strelka_variants.maf",
            "strelka/mutsigCV/somatic.sig_genes.txt",
            "mutect/oncotator/mutect_variants.maf",
            "mutect/mutsigCV/somatic.sig_genes.txt"

    output:
