rule rnafusioncleanup:
        input:  expand("{name}.RnaSeqMetrics.txt",name=samples),
#                "RawCountFile_genes_filtered.txt",
#                "RawCountFile_junctions_filtered.txt",
#                "RawCountFile_genejunctions_filtered.txt",
#                expand("{name}.star.count.overlap.txt",name=samples),
#                "RawCountFileOverlap.txt",
#                "RawCountFileStar.txt",
                expand("{name}.rsem.genes.results",name=samples),
                expand("{x}.R1.fastq.gz", x=samples),
                "RawCountFile_RSEM_genes_filtered.txt",
        output: expand("expression/{name}.RnaSeqMetrics.txt",name=samples),
#                "expression/RawCountFile_genes_filtered.txt",
#                "expression/RawCountFile_junctions_filtered.txt",
#                "expression/RawCountFile_genejunctions_filtered.txt",
#                expand("expression/{name}.star.count.overlap.txt",name=samples),
#                "expression/RawCountFileOverlap.txt",
#                "expression/RawCountFileStar.txt",
                expand("expression/{name}.rsem.genes.results",name=samples),
                "expression/RawCountFile_RSEM_genes_filtered.txt",
        params: rname="pl:clean"
        shell:  "mv *.rsem.stat expression/; mv *_STARgenome expression/; mv *.rsem.time expression/; mv *.rsem.isoforms.results expression/; mv *.star_rg_added.sorted.dmark.bai expression/; mv *.star.duplic expression/; mv RSEM_HistBeforenormFilter.png expression/; mv *_counts.txt expression/; mv *.InsertSizeMetrics.txt expression/; mv *.InsertSizeHisto.pdf expression/; mv *.flagstat.concord.txt expression/; mv *filtered.txt expression/; mv *.RnaSeqMetrics.txt expression/; mv *.rsem.genes.results expression/"