rule theta:
       params: normalsample=lambda wildcards: config['project']['pairs'][wildcards.x][0],tumorsample=lambda wildcards: config['project']['pairs'][wildcards.x][1],genome=config['references'][pfamily]['GENOME'],exons=config['references'][pfamily]['EXONS'],sites=config['references'][pfamily]['THETASNPS'],workdir=config['project']['workpath'],rname="pl:theta"
       input:  normal=lambda wildcards: config['project']['pairs'][wildcards.x][0]+".recal.bam",
               tumor=lambda wildcards: config['project']['pairs'][wildcards.x][1]+".recal.bam",
               calls=config['project']['workpath']+"/cnvkit_out/{x}_calls.cns",
               targets="exome_targets.bed",
               dir=config['project']['workpath']+"/theta_out"
       output: infile=config['project']['workpath']+"/theta_out/{x}/{x}.input",
               sampdir=config['project']['workpath']+"/theta_out/{x}"
       threads: 1
       shell:  "mkdir -p {output.sampdir}; ln -s {params.workdir}/{input.normal} {output.sampdir}/{input.normal}; ln -s {params.workdir}/{input.tumor} {output.sampdir}/{input.tumor}; cd {output.sampdir}; module load samtools; module load theta; CreateExomeInput -s {params.workdir}/cnvkit_out/{params.normalsample}+{params.tumorsample}_cnvkit/{params.tumorsample}.cns -t {input.tumor} -n {input.normal} --OUTPUT_PREFIX {params.normalsample}+{params.tumorsample} --FA {params.genome} --EXON_FILE {params.exons} --DIR={output.sampdir}; perl {params.workdir}/Scripts/make_theta_config.pl {params.normalsample} {params.tumorsample} {params.sites} {output.sampdir}; java -Xmx24g -jar $THETA_JARPATH/getAlleleCounts.jar {output.sampdir}/{params.tumorsample}.config; java -Xmx24g -jar $THETA_JARPATH/getAlleleCounts.jar {output.sampdir}/{params.normalsample}.config; RunTHetA {output.sampdir}/{params.normalsample}+{params.tumorsample}.input --TUMOR_FILE {output.sampdir}/{params.tumorsample}.withCounts --NORMAL_FILE {output.sampdir}/{params.normalsample}.withCounts --MIN_FRAC 0.0001 --NUM_PROCESSES {threads} --OUTPUT_PREFIX {params.tumorsample} --DIR {output.sampdir} --BAF"