rule theta:
       params: normalsample=lambda wildcards: config['project']['pairs'][wildcards.x][0],tumorsample=lambda wildcards: config['project']['pairs'][wildcards.x][1],genome=config['references'][pfamily]['GENOME'],exons=config['references'][pfamily]['EXONS'],sites=config['references'][pfamily]['THETASNPS'],workdir=config['project']['workpath'],rname="pl:theta"
       input:  normal=lambda wildcards: config['project']['pairs'][wildcards.x][0]+".recal.bam",
               tumor=lambda wildcards: config['project']['pairs'][wildcards.x][1]+".recal.bam",
               calls=config['project']['workpath']+"/cnvkit_out/{x}_calls.cns",
               targets="exome_targets.bed",
       output: infile=config['project']['workpath']+"/theta_out/{x}/{x}.input",
#               sampdir=config['project']['workpath']+"/theta_out/{x}"
       threads: 1
       shell:  "mkdir -p {params.workdir}/theta_out/{params.normalsample}+{params.tumorsample}; ln -s {params.workdir}/{input.normal} {params.workdir}/theta_out/{params.normalsample}+{params.tumorsample}/{input.normal}; ln -s {params.workdir}/{input.tumor} {params.workdir}/theta_out/{params.normalsample}+{params.tumorsample}/{input.tumor}; cd {params.workdir}/theta_out/{params.normalsample}+{params.tumorsample}; module load samtools; module load theta/0.7-5-g0d2ef5f; CreateExomeInput -s {params.workdir}/cnvkit_out/{params.normalsample}+{params.tumorsample}_cnvkit/{params.tumorsample}.cns -t {input.tumor} -n {input.normal} --OUTPUT_PREFIX {params.normalsample}+{params.tumorsample} --FA {params.genome} --EXON_FILE {params.exons} --DIR={params.workdir}/theta_out/{params.normalsample}+{params.tumorsample}; perl {params.workdir}/Scripts/make_theta_config.pl {params.normalsample} {params.tumorsample} {params.sites} {params.workdir}/theta_out/{params.normalsample}+{params.tumorsample}; java -Xmx24g -jar $THETA_JARPATH/getAlleleCounts.jar {params.workdir}/theta_out/{params.normalsample}+{params.tumorsample}/{params.tumorsample}.config; java -Xmx24g -jar $THETA_JARPATH/getAlleleCounts.jar {params.workdir}/theta_out/{params.normalsample}+{params.tumorsample}/{params.normalsample}.config; RunTHetA {params.workdir}/theta_out/{params.normalsample}+{params.tumorsample}/{params.normalsample}+{params.tumorsample}.input --TUMOR_FILE {params.workdir}/theta_out/{params.normalsample}+{params.tumorsample}/{params.tumorsample}.withCounts --NORMAL_FILE {params.workdir}/theta_out/{params.normalsample}+{params.tumorsample}/{params.normalsample}.withCounts --MIN_FRAC 0.0001 --NUM_PROCESSES {threads} --OUTPUT_PREFIX {params.tumorsample} --DIR {params.workdir}/theta_out/{params.normalsample}+{params.tumorsample} --BAF"