rule vardict:
       input:  normal=lambda wildcards: config['project']['pairs'][wildcards.x][0]+".recal.bam",
               tumor=lambda wildcards: config['project']['pairs'][wildcards.x][1]+".recal.bam",
               targets=config['project']['workpath']+"/exome_targets.bed",
               normalbai=lambda wildcards: config['project']['pairs'][wildcards.x][0]+".recal.bam.bai",
               tumorbai=lambda wildcards: config['project']['pairs'][wildcards.x][1]+".recal.bam.bai"
       output: vcf=temp(config['project']['workpath']+"/vardict_out/{x}.vcf"),
               filtvcf=config['project']['workpath']+"/vardict_out/{x}.FINAL.vcf",
               csvstats=config['project']['workpath']+"/vardict_out/{x}.vardict.stats.csv",
               htmlstats=config['project']['workpath']+"/vardict_out/{x}.vardict.stats.html",
               out=config['project']['workpath']+"/vardict_out/{x}.snpeff.out"
       params: normalsample=lambda wildcards: config['project']['pairs'][wildcards.x][0],tumorsample=lambda wildcards: config['project']['pairs'][wildcards.x][1],targets="exome_targets.bed",knowns=config['references'][pfamily]['MUTECTVARIANTS'],mutect=config['bin'][pfamily]['MUTECT'],gatk=config['bin'][pfamily]['GATK'],genome=config['references'][pfamily]['MUTECTGENOME'],cosmic=config['references'][pfamily]['MUTECTCOSMIC'],snp=config['references'][pfamily]['MUTECTSNP'],snpeffgenome=config['references'][pfamily]['SNPEFF_GENOME'],snpeff=config['bin'][pfamily]['SNPEFF'],effconfig=config['references'][pfamily]['SNPEFF_CONFIG'],pon=config['references'][pfamily]['PON'],rname="pl:vardict"
       shell:  "mkdir -p vardict_out; module load R/3.5; module load samtools/1.9; /data/CCBR_Pipeliner/db/PipeDB/bin/VarDict/vardict -G {params.genome} -f 0.05 -x 1000 -N {params.tumorsample} --nosv -b \"{input.tumor}|{input.normal}\" -t -Q 20 -c 1 -S 2 -E 3 {params.targets} | /data/CCBR_Pipeliner/db/PipeDB/bin/VarDict/testsomatic.R | /data/CCBR_Pipeliner/db/PipeDB/bin/VarDict/var2vcf_paired.pl -N {params.tumorsample} -f 0.05 > {output.vcf}; module load GATK/3.8-0; module load java/1.8.0_92; GATK -m 48G SelectVariants -R {params.genome} --variant {output.vcf} --excludeFiltered --discordance {params.pon} -o {output.filtvcf}; module load snpEff/4.3t; java -Xmx12g -jar $SNPEFF_JAR -v {params.snpeffgenome} -c {params.effconfig} -interval {params.targets} -cancer -canon -csvStats {output.csvstats} -stats {output.htmlstats} -cancerSamples pairs {output.filtvcf} > {output.out}"